version: '3'

services:
  mlist-frontend:
    build: .
    ports:
      - '80:80'
    volumes:
      - './nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - mlist-backend

  mlist-backend:
    command: ["/app/config.yaml"]
    image: olegdayo/mlist-backend:latest
    ports:
      - '8080:8080'
    volumes:
      - './config/config.yaml:/app/config.yaml:ro'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1
    hostname: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 10s
